name: Build and deploy

on:
  push:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
      - uses: actions/checkout@v3
      - name: build
      - uses: uses: docker/build-push-action@latest
        with:
          context: .
          push: false
